
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.7.2+d6990bcfa for .NET Framework
      Build started 02.12.2023 23:14:54.
      
      Project "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:03.30
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/olexa/Documents/Мій код/Навчання/Університет/2 курс/Додаткові розділи С++/Лабораторні роботи/3 lab/prog/CMakeFiles/3.26.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.7.2+d6990bcfa for .NET Framework
      Build started 02.12.2023 23:14:59.
      
      Project "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:02.69
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/olexa/Documents/Мій код/Навчання/Університет/2 курс/Додаткові розділи С++/Лабораторні роботи/3 lab/prog/CMakeFiles/3.26.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/olexa/Documents/\u041c\u0456\u0439 \u043a\u043e\u0434/\u041d\u0430\u0432\u0447\u0430\u043d\u043d\u044f/\u0423\u043d\u0456\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442/2 \u043a\u0443\u0440\u0441/\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u0440\u043e\u0437\u0434\u0456\u043b\u0438 \u0421++/\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u0456 \u0440\u043e\u0431\u043e\u0442\u0438/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-fska7d"
      binary: "C:/Users/olexa/Documents/\u041c\u0456\u0439 \u043a\u043e\u0434/\u041d\u0430\u0432\u0447\u0430\u043d\u043d\u044f/\u0423\u043d\u0456\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442/2 \u043a\u0443\u0440\u0441/\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u0440\u043e\u0437\u0434\u0456\u043b\u0438 \u0421++/\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u0456 \u0440\u043e\u0431\u043e\u0442\u0438/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-fska7d"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/olexa/Documents/Мій код/Навчання/Університет/2 курс/Додаткові розділи С++/Лабораторні роботи/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-fska7d
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_de1b7.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.7.2+d6990bcfa for .NET Framework
        Build started 02.12.2023 23:15:03.
        
        Project "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-fska7d\\cmTC_de1b7.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_de1b7.dir\\Debug\\".
          Creating directory "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-fska7d\\Debug\\".
          Creating directory "cmTC_de1b7.dir\\Debug\\cmTC_de1b7.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_de1b7.dir\\Debug\\cmTC_de1b7.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_de1b7.dir\\Debug\\cmTC_de1b7.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_de1b7.dir\\Debug\\\\" /Fd"cmTC_de1b7.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_de1b7.dir\\Debug\\\\" /Fd"cmTC_de1b7.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-fska7d\\Debug\\cmTC_de1b7.exe" /INCREMENTAL /ILK:"cmTC_de1b7.dir\\Debug\\cmTC_de1b7.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/olexa/Documents/М?й код/Навчання/Ун?верситет/2 курс/Додатков? розд?ли С++/Лабораторн? роботи/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-fska7d/Debug/cmTC_de1b7.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/olexa/Documents/М?й код/Навчання/Ун?верситет/2 курс/Додатков? розд?ли С++/Лабораторн? роботи/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-fska7d/Debug/cmTC_de1b7.lib" /MACHINE:X64  /machine:x64 cmTC_de1b7.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_de1b7.vcxproj -> C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-fska7d\\Debug\\cmTC_de1b7.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_de1b7.dir\\Debug\\cmTC_de1b7.tlog\\unsuccessfulbuild".
          Touching "cmTC_de1b7.dir\\Debug\\cmTC_de1b7.tlog\\cmTC_de1b7.lastbuildstate".
        Done Building Project "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-fska7d\\cmTC_de1b7.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:02.66
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/olexa/Documents/\u041c\u0456\u0439 \u043a\u043e\u0434/\u041d\u0430\u0432\u0447\u0430\u043d\u043d\u044f/\u0423\u043d\u0456\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442/2 \u043a\u0443\u0440\u0441/\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u0440\u043e\u0437\u0434\u0456\u043b\u0438 \u0421++/\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u0456 \u0440\u043e\u0431\u043e\u0442\u0438/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-ry9zpn"
      binary: "C:/Users/olexa/Documents/\u041c\u0456\u0439 \u043a\u043e\u0434/\u041d\u0430\u0432\u0447\u0430\u043d\u043d\u044f/\u0423\u043d\u0456\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442/2 \u043a\u0443\u0440\u0441/\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u0440\u043e\u0437\u0434\u0456\u043b\u0438 \u0421++/\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u0456 \u0440\u043e\u0431\u043e\u0442\u0438/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-ry9zpn"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/olexa/Documents/Мій код/Навчання/Університет/2 курс/Додаткові розділи С++/Лабораторні роботи/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-ry9zpn
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_70309.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.7.2+d6990bcfa for .NET Framework
        Build started 02.12.2023 23:15:07.
        
        Project "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-ry9zpn\\cmTC_70309.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_70309.dir\\Debug\\".
          Creating directory "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-ry9zpn\\Debug\\".
          Creating directory "cmTC_70309.dir\\Debug\\cmTC_70309.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_70309.dir\\Debug\\cmTC_70309.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_70309.dir\\Debug\\cmTC_70309.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_70309.dir\\Debug\\\\" /Fd"cmTC_70309.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_70309.dir\\Debug\\\\" /Fd"cmTC_70309.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-ry9zpn\\Debug\\cmTC_70309.exe" /INCREMENTAL /ILK:"cmTC_70309.dir\\Debug\\cmTC_70309.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/olexa/Documents/М?й код/Навчання/Ун?верситет/2 курс/Додатков? розд?ли С++/Лабораторн? роботи/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-ry9zpn/Debug/cmTC_70309.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/olexa/Documents/М?й код/Навчання/Ун?верситет/2 курс/Додатков? розд?ли С++/Лабораторн? роботи/3 lab/prog/CMakeFiles/CMakeScratch/TryCompile-ry9zpn/Debug/cmTC_70309.lib" /MACHINE:X64  /machine:x64 cmTC_70309.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_70309.vcxproj -> C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-ry9zpn\\Debug\\cmTC_70309.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_70309.dir\\Debug\\cmTC_70309.tlog\\unsuccessfulbuild".
          Touching "cmTC_70309.dir\\Debug\\cmTC_70309.tlog\\cmTC_70309.lastbuildstate".
        Done Building Project "C:\\Users\\olexa\\Documents\\М?й код\\Навчання\\Ун?верситет\\2 курс\\Додатков? розд?ли С++\\Лабораторн? роботи\\3 lab\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-ry9zpn\\cmTC_70309.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:04.17
        
      exitCode: 0
...
